### ISSUE TITLE
Support for automatic dark theme palette 

### ISSUE THREAD

**Issue by marcfilleul** [evilmartians/harmony#1]
What an amazing palette! I've been looking for this kind of mirrored contrast palette for a while and this one is awesome, so thanks for your work.

I'm using colors with semantic names (primary, secondary...), here is my tailwind config for that part:
![harmony-palette-tailwind](https://github.com/evilmartians/harmony/assets/3406688/c3b9b1a2-661b-437d-9faa-71f7b0375c9d)

I'd like to be able to use only one color class on a given element:
`<h1 class="text-primary-900">My title</h1>`

And to have automatically the mirrored color when applying dark mode.

What would be the easiest way to do that with your palette? (I could use CSS variables and all that stuff but was wondering if there is an easier way).

Thanks a lot.

**Comment by 11bit** [comment]
Hey @marcfilleul! 
The last time I needed dark theme I ended up implementing the same approach with CSS variables. Unfortunately, I don't know any better solution for tailwind because of the way it works. There is a [tw-colors](https://github.com/L-Blondy/tw-colors) plugin, but as far as I know, it also uses css variables inside

**Comment by marcfilleul** [comment]
Thanks!
